name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and test ${{ matrix.name }}
    runs-on: ${{ matrix.os || 'ubuntu-latest' }}

    steps:
      - uses: actions/checkout@v4
      - run: |
          ./build.sh
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: ugrep-indexer
          path: bin/ugrep-indexer
